#!/usr/bin/env bash

#MISE description="Run the Rust tests for this project"
#MISE sources=["Cargo.toml", "src/**/*.rs"]

echo "🚀 Starting Crumbs Rust tests..."
proj_dir=$(git rev-parse --show-toplevel)
cd "$proj_dir" || exit 1

set -euo pipefail

cargo nextest run --workspace
